<?php
$servicesData = [
    'business-id-cards' => [
        'title' => 'Business & ID Cards',
        'hero_title' => 'Business Cards & ID Cards That Look Premium',
        'hero_subtitle' => 'Smart designs, clean print quality, and durable finishes for teams, schools, and businesses.',
        'hero_image' => 'https://images.unsplash.com/photo-1556740758-90de374c12ad?q=80&w=1400',
        'category_intro' => 'Choose card type first, then pick finish, lamination, and quantity.',
        'categories' => [
            ['name' => 'Business Cards', 'icon' => 'bi-person-vcard', 'description' => 'Minimal, premium, matte, glossy, and spot-UV styles.'],
            ['name' => 'Corporate ID Cards', 'icon' => 'bi-badge-id', 'description' => 'Employee cards with barcode, photo, and secure layouts.'],
            ['name' => 'College ID Cards', 'icon' => 'bi-mortarboard', 'description' => 'Student and faculty card formats with institute branding.'],
            ['name' => 'Visitor / Event Pass', 'icon' => 'bi-ticket-perforated', 'description' => 'Quick-issue access passes for events and offices.'],
        ],
        'products' => [
            ['name' => 'Premium Matte Business Card', 'price' => '$22.00 / 100', 'image' => 'https://images.unsplash.com/photo-1589330694653-efa6475653db?q=80&w=900'],
            ['name' => 'PVC Smart ID Card', 'price' => '$55.00 / 50', 'image' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?q=80&w=900'],
            ['name' => 'Spot UV Visiting Card', 'price' => '$30.00 / 100', 'image' => 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=900'],
        ],
        'features' => ['Sharp text and photo clarity', 'Water-resistant and scratch-resistant options', 'Fast design proof turnaround', 'Bulk pricing for institutions'],
        'process' => [
            ['title' => 'Share Details', 'description' => 'Send logo, contact details, and preferred card style.'],
            ['title' => 'Approve Preview', 'description' => 'Review digital proof and request final edits.'],
            ['title' => 'Print & Dispatch', 'description' => 'Quality check, finish, and quick delivery.'],
        ],
        'faq' => [
            ['question' => 'Can I print cards with different names in one order?', 'answer' => 'Yes. We support variable data printing for teams and institutions.'],
            ['question' => 'Do you provide lanyards with ID cards?', 'answer' => 'Yes, optional lanyards, card holders, and clips are available.'],
            ['question' => 'What file format do you accept?', 'answer' => 'PDF, AI, PSD, and high-resolution PNG/JPG are accepted.'],
        ],
    ],
    'office-stationery' => [
        'title' => 'Office Stationery Supplies',
        'hero_title' => 'Customized Office Stationery Supplies',
        'hero_subtitle' => 'Build a consistent brand presence across daily office stationery and communication materials.',
        'hero_image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1400',
        'category_intro' => 'Select your stationery category, then personalize format, material, and quantity.',
        'categories' => [
            ['name' => 'Letterheads', 'icon' => 'bi-file-earmark-text', 'description' => 'Professional branded letterheads for formal communication.'],
            ['name' => 'Envelopes', 'icon' => 'bi-envelope-paper', 'description' => 'Corporate envelopes in multiple sizes and paper stocks.'],
            ['name' => 'Notepads', 'icon' => 'bi-journal-text', 'description' => 'Custom office pads and memo blocks for teams.'],
            ['name' => 'Folders & Files', 'icon' => 'bi-folder2-open', 'description' => 'Presentation folders and document holders with logo branding.'],
        ],
        'products' => [
            ['name' => 'Executive Letterhead Pack', 'price' => '$28.00 / 100', 'image' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=900'],
            ['name' => 'Branded Envelope Set', 'price' => '$18.00 / 100', 'image' => 'https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=900'],
            ['name' => 'Company Notepad Bundle', 'price' => '$24.00 / 50', 'image' => 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=900'],
        ],
        'features' => ['Consistent brand identity across materials', 'Multiple paper GSM and textures', 'Clean print with edge-to-edge options', 'Easy reorder for recurring office needs'],
        'process' => [
            ['title' => 'Select Items', 'description' => 'Choose stationery sets based on your office workflow.'],
            ['title' => 'Apply Branding', 'description' => 'Add logo, brand colors, and content templates.'],
            ['title' => 'Production & Delivery', 'description' => 'Printed, packed, and delivered with reorder support.'],
        ],
        'faq' => [
            ['question' => 'Do you offer combo packs for full office setup?', 'answer' => 'Yes, we provide bundled pricing for complete stationery kits.'],
            ['question' => 'Can you match exact brand colors?', 'answer' => 'Yes, we support Pantone/CMYK-guided color matching.'],
            ['question' => 'Is there a minimum order quantity?', 'answer' => 'MOQ varies by product, but low-volume options are available.'],
        ],
    ],
    'college-photo-frames' => [
        'title' => 'College Photo Frames',
        'hero_title' => 'Customized College Photo Frames',
        'hero_subtitle' => 'Design memorable graduation, department, and event photo frames with premium finishing.',
        'hero_image' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1400',
        'category_intro' => 'Choose frame style first for your campus photos, then finalize size and mounting.',
        'categories' => [
            ['name' => 'Graduation Frames', 'icon' => 'bi-award', 'description' => 'Elegant frames for convocation and certificate celebrations.'],
            ['name' => 'Department Collages', 'icon' => 'bi-grid-3x3-gap', 'description' => 'Batch and class collage layouts for campus walls.'],
            ['name' => 'Memory Wall Frames', 'icon' => 'bi-image', 'description' => 'Large curated sets for alumni halls and offices.'],
            ['name' => 'Sports & Club Frames', 'icon' => 'bi-trophy', 'description' => 'Achievement and event highlights in custom formats.'],
        ],
        'products' => [
            ['name' => 'Graduation Signature Frame', 'price' => '$38.00', 'image' => 'https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?q=80&w=900'],
            ['name' => 'College Batch Collage Frame', 'price' => '$52.00', 'image' => 'https://images.unsplash.com/photo-1511377107391-116a6d9f6535?q=80&w=900'],
            ['name' => 'Department Wall Frame Set', 'price' => '$95.00', 'image' => 'https://images.unsplash.com/photo-1470163395405-d2b80e7450ed?q=80&w=900'],
        ],
        'features' => ['Custom sizes for classrooms and halls', 'Matte and gloss frame finishes', 'High-resolution color correction', 'Long-lasting mounting quality'],
        'process' => [
            ['title' => 'Collect Photos', 'description' => 'Share student/group images and event details.'],
            ['title' => 'Frame Layout Design', 'description' => 'Approve collage composition and text labels.'],
            ['title' => 'Print, Frame & Install', 'description' => 'Production with optional delivery and installation support.'],
        ],
        'faq' => [
            ['question' => 'Can you design frames for entire departments?', 'answer' => 'Yes, we handle both single pieces and campus-scale batches.'],
            ['question' => 'Do you provide wall mounting accessories?', 'answer' => 'Yes, hooks and mounting kits can be included.'],
            ['question' => 'Can we add institute logo and year?', 'answer' => 'Yes, full customization with logos, batch names, and year marks is available.'],
        ],
    ],
    'wall-display' => [
        'title' => 'Wall Display Printing',
        'hero_title' => 'Creative Wall Display Solutions',
        'hero_subtitle' => 'Turn blank walls into branded stories with display panels, poster walls, and custom graphics.',
        'hero_image' => 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=1400',
        'category_intro' => 'Start with display type, then select material, size, and finishing style.',
        'categories' => [
            ['name' => 'Office Wall Branding', 'icon' => 'bi-building', 'description' => 'Mission walls, reception branding, and culture displays.'],
            ['name' => 'College Display Walls', 'icon' => 'bi-bank', 'description' => 'Department timelines and achievement walls for campuses.'],
            ['name' => 'Gallery Panels', 'icon' => 'bi-easel2', 'description' => 'Exhibition-ready panel and mounted print solutions.'],
            ['name' => 'Retail Visual Displays', 'icon' => 'bi-shop', 'description' => 'Window graphics, in-store posters, and thematic walls.'],
        ],
        'products' => [
            ['name' => 'Acrylic Mounted Display', 'price' => '$65.00', 'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?q=80&w=900'],
            ['name' => 'Canvas Wall Panel', 'price' => '$48.00', 'image' => 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=900'],
            ['name' => 'Vinyl Wall Graphic Kit', 'price' => '$72.00', 'image' => 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=900'],
        ],
        'features' => ['UV-stable inks for longer life', 'Site-specific measurement support', 'Multiple substrate choices', 'Installation guidance and support'],
        'process' => [
            ['title' => 'Site & Requirement Brief', 'description' => 'Share wall dimensions and desired visual direction.'],
            ['title' => 'Layout + Mockup', 'description' => 'Review the scaled preview before print.'],
            ['title' => 'Production & Setup', 'description' => 'Print, finish, and optional on-site installation.'],
        ],
        'faq' => [
            ['question' => 'Do you handle very large wall sizes?', 'answer' => 'Yes, we produce modular panels for large installations.'],
            ['question' => 'Which material is best for indoor office walls?', 'answer' => 'Acrylic or high-quality vinyl is preferred for clean and durable results.'],
            ['question' => 'Can displays be removed without damaging walls?', 'answer' => 'Yes, removable options are available for temporary campaigns.'],
        ],
    ],
    'digital-printing' => [
        'title' => 'Digital Printing',
        'hero_title' => 'High-Quality Digital Printing',
        'hero_subtitle' => 'Professional digital printing for marketing, events, and day-to-day business requirements.',
        'hero_image' => 'https://images.unsplash.com/photo-1563200787-83281c76e6a1?q=80&w=1400',
        'category_intro' => 'Choose print format first, then paper type, finish, and quantity.',
        'categories' => [
            ['name' => 'Business Marketing', 'icon' => 'bi-briefcase', 'description' => 'Cards, brochures, and flyers for promotions.'],
            ['name' => 'Event Prints', 'icon' => 'bi-calendar-event', 'description' => 'Posters, invites, and handouts for events.'],
            ['name' => 'Corporate Material', 'icon' => 'bi-file-earmark-richtext', 'description' => 'Reports, pitch decks, and brand collateral.'],
            ['name' => 'Bulk Print Jobs', 'icon' => 'bi-layers', 'description' => 'Fast and scalable print runs with quality control.'],
        ],
        'products' => [
            ['name' => 'Business Cards', 'price' => '$25.00 / 100', 'image' => 'https://images.unsplash.com/photo-1589330694653-efa6475653db?q=80&w=900'],
            ['name' => 'Brochures', 'price' => '$40.00 / 50', 'image' => 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?q=80&w=900'],
            ['name' => 'Event Flyers', 'price' => '$30.00 / 100', 'image' => 'https://images.unsplash.com/photo-1604147706283-d7119b5b822c?q=80&w=900'],
        ],
        'features' => ['Fast turnaround', 'Premium paper choices', 'Bulk discounts', 'Sharp color and detail'],
        'process' => [
            ['title' => 'Upload Files', 'description' => 'Share ready design files or request design support.'],
            ['title' => 'Approve Print Proof', 'description' => 'Confirm final preview before production.'],
            ['title' => 'Print & Deliver', 'description' => 'Accurate printing and timely dispatch.'],
        ],
        'faq' => [
            ['question' => 'Can I place urgent same-day orders?', 'answer' => 'Yes, for selected formats and quantities.'],
            ['question' => 'Do you provide matte and glossy finish options?', 'answer' => 'Yes, both options are available across most products.'],
            ['question' => 'Do you check file quality before printing?', 'answer' => 'Yes, a preflight check is done for resolution and bleed setup.'],
        ],
    ],
    'photo-frames' => [
        'title' => 'Photo Frames Printing',
        'hero_title' => 'Premium Photo Frames',
        'hero_subtitle' => 'Turn your moments into masterpieces with premium frame quality and rich print detail.',
        'hero_image' => 'https://images.unsplash.com/photo-1543880562-b43a90300483?q=80&w=1400',
        'category_intro' => 'Pick frame style and size first, then select glass, mount, and finish.',
        'categories' => [
            ['name' => 'Classic Frames', 'icon' => 'bi-border-all', 'description' => 'Timeless wood and matte options for portraits.'],
            ['name' => 'Modern Metal Frames', 'icon' => 'bi-bounding-box', 'description' => 'Contemporary clean-edge metallic designs.'],
            ['name' => 'Collage Frames', 'icon' => 'bi-grid', 'description' => 'Multiple photos in a single artistic layout.'],
            ['name' => 'Tabletop Frames', 'icon' => 'bi-card-image', 'description' => 'Compact desk-ready premium frame prints.'],
        ],
        'products' => [
            ['name' => 'Wooden Classic Frame', 'price' => '$25.00', 'image' => 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?q=80&w=900'],
            ['name' => 'Modern Metal Frame', 'price' => '$30.00', 'image' => 'https://images.unsplash.com/photo-1513519965159-450fdfcecb04?q=80&w=900'],
            ['name' => 'Collage Frame', 'price' => '$40.00', 'image' => 'https://images.unsplash.com/photo-1588698943640-5b128795db0f?q=80&w=900'],
        ],
        'features' => ['Vibrant colors', 'Multiple sizes', 'Wall mount ready', 'Premium glass protection'],
        'process' => [
            ['title' => 'Choose Layout', 'description' => 'Select single photo, collage, or themed layouts.'],
            ['title' => 'Finalize Frame Style', 'description' => 'Pick material, color, and mount type.'],
            ['title' => 'Print & Frame', 'description' => 'Careful finishing and secure packaging.'],
        ],
        'faq' => [
            ['question' => 'Can I order custom frame sizes?', 'answer' => 'Yes, custom dimensions are available.'],
            ['question' => 'Do you offer anti-glare glass?', 'answer' => 'Yes, anti-glare and clear glass options are supported.'],
            ['question' => 'Can you create frames from phone photos?', 'answer' => 'Yes, if image quality is sufficient for print size.'],
        ],
    ],
    'cup-printing' => [
        'title' => 'Cup Printing',
        'hero_title' => 'Personalized Mugs & Cups',
        'hero_subtitle' => 'Create personalized mugs and cups for gifting, branding, and event campaigns.',
        'hero_image' => 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?q=80&w=1400',
        'category_intro' => 'Select cup material and style first, then personalize artwork and quantity.',
        'categories' => [
            ['name' => 'Ceramic Mugs', 'icon' => 'bi-cup-hot', 'description' => 'Everyday coffee mugs with vivid print output.'],
            ['name' => 'Magic Mugs', 'icon' => 'bi-stars', 'description' => 'Heat-reactive mugs for surprise reveal prints.'],
            ['name' => 'Travel Tumblers', 'icon' => 'bi-thermometer-half', 'description' => 'Insulated options for on-the-go branding.'],
            ['name' => 'Gift Sets', 'icon' => 'bi-gift', 'description' => 'Custom mug packs for festivals and teams.'],
        ],
        'products' => [
            ['name' => 'Magic Mug', 'price' => '$20.00', 'image' => 'https://images.unsplash.com/photo-1533036662494-df004b7ac816?q=80&w=900'],
            ['name' => 'Classic White Mug', 'price' => '$10.00', 'image' => 'https://images.unsplash.com/photo-1555938166-31a8bc59e9ef?q=80&w=900'],
            ['name' => 'Travel Tumbler', 'price' => '$22.00', 'image' => 'https://images.unsplash.com/photo-1596489397664-9ed6cc3b063d?q=80&w=900'],
        ],
        'features' => ['Microwave safe options', 'Fade-resistant prints', 'Durable ceramic and steel options', 'Gift-ready packaging'],
        'process' => [
            ['title' => 'Pick Cup Type', 'description' => 'Select style, size, and base material.'],
            ['title' => 'Add Design', 'description' => 'Upload photo, text, or brand logo.'],
            ['title' => 'Print & Pack', 'description' => 'Final production with secure packaging.'],
        ],
        'faq' => [
            ['question' => 'Can I print individual names on each mug?', 'answer' => 'Yes, variable name customization is supported.'],
            ['question' => 'Are printed mugs dishwasher safe?', 'answer' => 'Yes, selected print methods are dishwasher friendly.'],
            ['question' => 'Do you offer bulk corporate gift orders?', 'answer' => 'Yes, bulk orders with volume discounts are available.'],
        ],
    ],
    'accessories-decoration' => [
        'title' => 'Accessories Decoration',
        'hero_title' => 'Decor Accessories',
        'hero_subtitle' => 'Enhance your space with custom accessories that combine function with personal style.',
        'hero_image' => 'https://images.unsplash.com/photo-1513694203232-719ea280e022?q=80&w=1400',
        'category_intro' => 'Choose decor accessory type first, then customize style, print, and finish.',
        'categories' => [
            ['name' => 'Cushions', 'icon' => 'bi-flower1', 'description' => 'Custom photo and typography cushion covers.'],
            ['name' => 'Wall Tapestries', 'icon' => 'bi-brush', 'description' => 'Large-format decorative fabric prints.'],
            ['name' => 'Coasters', 'icon' => 'bi-circle-square', 'description' => 'Table-ready branded and custom coaster sets.'],
            ['name' => 'Desk Decor', 'icon' => 'bi-lamp', 'description' => 'Creative tabletop printed accessories.'],
        ],
        'products' => [
            ['name' => 'Custom Cushions', 'price' => '$15.00', 'image' => 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e6?q=80&w=900'],
            ['name' => 'Wall Tapestries', 'price' => '$35.00', 'image' => 'https://images.unsplash.com/photo-1522758971460-1d21fac222d1?q=80&w=900'],
            ['name' => 'Table Coasters', 'price' => '$8.00', 'image' => 'https://images.unsplash.com/photo-1599553556096-7ac25c1b694c?q=80&w=900'],
        ],
        'features' => ['HD print quality', 'Eco-friendly inks', 'Washable materials', 'Creative design templates'],
        'process' => [
            ['title' => 'Select Decor Type', 'description' => 'Choose utility or display-focused items.'],
            ['title' => 'Customize Artwork', 'description' => 'Add logos, colors, and personalized text.'],
            ['title' => 'Produce & Deliver', 'description' => 'Finalize quality check and shipping.'],
        ],
        'faq' => [
            ['question' => 'Can I order mixed decor products in one batch?', 'answer' => 'Yes, mixed item bundles are supported.'],
            ['question' => 'Are the colors fade resistant?', 'answer' => 'Yes, print methods are optimized for long-term use.'],
            ['question' => 'Can you help with design ideas?', 'answer' => 'Yes, our team can share layout concepts before print.'],
        ],
    ],
    'phone-back-cover' => [
        'title' => 'Phone Back Cover Printing',
        'hero_title' => 'Custom Phone Cases',
        'hero_subtitle' => 'Protect your phone with style and personalize your back cover with your favorite memories.',
        'hero_image' => 'https://images.unsplash.com/photo-1603539947678-ebda0d00cece?q=80&w=1400',
        'category_intro' => 'Start with case model and finish, then customize with photos, text, or branding.',
        'categories' => [
            ['name' => 'Matte Cases', 'icon' => 'bi-phone', 'description' => 'Smooth anti-glare covers with elegant appearance.'],
            ['name' => 'Glossy Hard Cases', 'icon' => 'bi-phone-flip', 'description' => 'Shiny high-color finish for vivid output.'],
            ['name' => 'Transparent Cases', 'icon' => 'bi-phone-vibrate', 'description' => 'Clear case style preserving original look.'],
            ['name' => 'Bumper Cases', 'icon' => 'bi-shield-check', 'description' => 'Protection-focused case designs with print zone.'],
        ],
        'products' => [
            ['name' => 'Matte Finish Cover', 'price' => '$15.00', 'image' => 'https://images.unsplash.com/photo-1541344845511-b8ae3e0b040e?q=80&w=900'],
            ['name' => 'Glossy Hard Case', 'price' => '$18.00', 'image' => 'https://images.unsplash.com/photo-1586522302821-ca41bc02d514?q=80&w=900'],
            ['name' => 'Transparent Bumper', 'price' => '$12.00', 'image' => 'https://images.unsplash.com/photo-1563202970-2005a9ee9111?q=80&w=900'],
        ],
        'features' => ['High-quality print', 'Scratch resistant options', 'Perfect fit models', 'Durable materials'],
        'process' => [
            ['title' => 'Choose Phone Model', 'description' => 'Select exact phone model and case style.'],
            ['title' => 'Upload Design', 'description' => 'Add artwork or request custom design assistance.'],
            ['title' => 'Print & Ship', 'description' => 'Precision printing, quality check, and dispatch.'],
        ],
        'faq' => [
            ['question' => 'Can I preview design before printing?', 'answer' => 'Yes, we share a digital preview for approval.'],
            ['question' => 'Do prints peel off over time?', 'answer' => 'Our print process is built for long-lasting durability.'],
            ['question' => 'Are all major phone brands supported?', 'answer' => 'Yes, most iOS and Android device models are available.'],
        ],
    ],
    'all-printing' => [
        'title' => 'All Printing Services',
        'hero_title' => 'Comprehensive Printing Solutions',
        'hero_subtitle' => 'From cards and stationery to large displays, get complete printing support in one place.',
        'hero_image' => 'https://images.unsplash.com/photo-1587582522791-ebd2395d9703?q=80&w=1400',
        'category_intro' => 'Explore by category first to quickly find products relevant to your project.',
        'categories' => [
            ['name' => 'Cards & Identity', 'icon' => 'bi-credit-card-2-front', 'description' => 'Business cards, ID cards, and visitor passes.'],
            ['name' => 'Office Stationery', 'icon' => 'bi-clipboard2', 'description' => 'Letterheads, envelopes, notepads, and folders.'],
            ['name' => 'Frames & Displays', 'icon' => 'bi-columns-gap', 'description' => 'Photo frames, wall displays, and mounted graphics.'],
            ['name' => 'Gifts & Accessories', 'icon' => 'bi-bag-heart', 'description' => 'Mugs, decor items, and custom accessories.'],
        ],
        'products' => [
            ['name' => 'T-Shirt Printing', 'price' => '$15.00', 'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=900'],
            ['name' => 'Large Banners', 'price' => '$50.00', 'image' => 'https://images.unsplash.com/photo-1559281363-241508f75432?q=80&w=900'],
            ['name' => 'Sticker Sheets', 'price' => '$10.00', 'image' => 'https://images.unsplash.com/photo-1600813337965-0c7f0f6795b2?q=80&w=900'],
        ],
        'features' => ['Versatile printing range', 'Custom size support', 'Expert design guidance', 'Reliable shipping'],
        'process' => [
            ['title' => 'Choose Category', 'description' => 'Pick the service type aligned to your need.'],
            ['title' => 'Finalize Products', 'description' => 'Select products, quantities, and customization.'],
            ['title' => 'Produce & Deliver', 'description' => 'Quality production and timely delivery at scale.'],
        ],
        'faq' => [
            ['question' => 'Can I combine multiple services in one order?', 'answer' => 'Yes, combined orders are supported with centralized coordination.'],
            ['question' => 'Do you handle bulk institutional orders?', 'answer' => 'Yes, we support large-volume education and enterprise projects.'],
            ['question' => 'Can you help with design from scratch?', 'answer' => 'Yes, our team can assist with complete design creation.'],
        ],
    ],
];
